
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'models.dart';
import 'screens/main_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  
  // Register Adapters (Generated by build_runner)
  // Hive.registerAdapter(TransactionAdapter());
  // Hive.registerAdapter(CategoryAdapter());
  // Hive.registerAdapter(AppSettingsAdapter());

  await Hive.openBox<Transaction>('transactions');
  await Hive.openBox<Category>('categories');
  await Hive.openBox('settings');

  runApp(const ZenSpendApp());
}

class ZenSpendApp extends StatelessWidget {
  const ZenSpendApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ZenSpend',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF101D22),
        primaryColor: const Color(0xFF13B6EC),
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF13B6EC),
          secondary: Color(0xFF10B981),
          surface: Color(0xFF192D33),
          onSurface: Colors.white,
        ),
        fontFamily: 'Inter',
      ),
      home: const MainScreen(),
    );
  }
}
